//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnosi()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public string DiagnosedProblem { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Symptoms { get; set; }
        public string Temperature { get; set; }
        public string BloodPressure { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
