//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public string MedsID { get; set; }
        public string Name { get; set; }
        public string Formula { get; set; }
        public string Formulation { get; set; }
        public string SideEffects { get; set; }
        public Nullable<bool> Availablity { get; set; }
    }
}
