//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionID { get; set; }
        public Nullable<int> DiagnoseID { get; set; }
        public string Medicine { get; set; }
        public string Dosage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Time { get; set; }
    
        public virtual Diagnosi Diagnosi { get; set; }
        public virtual Medicine Medicine1 { get; set; }
    }
}
